install.packages("tidyverse")
install.packages("devtools")
install.packages("ggplot2")
install.packages("dplyr")
install.packages("DT")
install.packages("stringr")
install.packages("sf")
install.packages("rnaturalearth")

library(devtools)
install_github("iobis/robis")
install_github("iobis/obistools")
install_github("ropensci/finch")